/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package se.sodapop.timeofday

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test fun `true`() {
        assertTrue(true)
    }
}
